### ISSUE TITLE
Convert files using <table> to use <div>

### ISSUE THREAD

**Issue by dscotese** [voluntaryist/site#1]
Bryce James explained that wherever there is a `<table>` in a page, it should be replaced so that bootstrap.js will treat it well when rendering the page on a mobile device.  Here is the replacement:

``` html
<div class="container"> (Equivalent to <table>)
  <div class="row"> (Equivalent to <tr>)
    <div class="col-xs-12"> (Equivalent to a single full-width <td> across all screens)
    </div>
  </div>
</div>
```

**Comment by dscotese** [comment]
I will be closing this issue in a few days because it seems wiser to use WordPress (Issue #3).  If anyone has input, please comment before then.

**Comment by dscotese** [comment]
We've decided that we will make the site mobile friendly by converting it to WordPress.

**Comment by Shepardh1** [comment]
Awesome, sorry I don't have my section done yet...

_Shepard Humphries' Vision http://shepardhumphries.com/vision.html | *
Entrepreneur_ |  *_www.ShootInJH.com_ http://www.shootinjh.com/
_Jackson Hole Shooting Experience  |  *_Proudly the international leader in
luxury entertainment shooting.*
-    http://www.linkedin.com/pub/shepard-humphries/14/53/80b*

https://www.tripadvisor.com/UserReviewEdit-g1798760-d1909756-e__2F__Attraction__5F__Review__2D__g1798760__2D__d1909756__2D__Reviews__2D__Jackson__5F__Hole__5F__Shooting__5F__Experience__2D__Jackson__5F__Hole__5F__Wyoming__2E__html-Jackson_Hole_Shooting_Experience-Jackson_Hole_Wyoming.html

https://www.tripadvisor.com/UserReviewEdit-g1798760-d1909756-e__2F__Attraction__5F__Review__2D__g1798760__2D__d1909756__2D__Reviews__2D__Jackson__5F__Hole__5F__Shooting__5F__Experience__2D__Jackson__5F__Hole__5F__Wyoming__2E__html-Jackson_Hole_Shooting_Experience-Jackson_Hole_Wyoming.html
