### ISSUE TITLE
HTTPS not implemented

### ISSUE THREAD

**Issue by lamorley** [voluntaryist/site#25]
Hey, don't know if anyone is managing this site anymore. If there is I would like to help.

**Comment by dscotese** [comment]
I am maintaining it.  I have not been able to buy a new SSL certificate yet but I am working on it.  Thanks for the reminder!  It should be fixed within a day or two.

**Comment by dscotese** [comment]
It's fixed now.  Thanks for the reminder!

**Comment by lamorley** [comment]
> It's fixed now. Thanks for the reminder!

Awesome! Thanks for supporting freedom!
