### ISSUE TITLE
WordPress Theme

### ISSUE THREAD

**Issue by dscotese** [voluntaryist/site#3]
It seems like the easiest way to make the site mobile-friendly is to use a framework that already does this and simply add our content into that framework.  I've chosen WordPress to do this.

This issue is for the creation (or modification) of an existing free (or donated) theme to match the way the site looks now.

**Comment by Shepardh1** [comment]
Worpress I know a little bit...

**Comment by lastgeniusleft2004** [comment]
Hi dscotese,
we have a very good team in wordpress, drupal,joomla,magento, php etc and we are in mobile app development,HTML5 will be best for you for mobile rendering, i mean mobile load time will be very speed even it can be done using wordpress and we can use Jquery for good look and feel for the site, you can visit our site www.whitefairapps.com we are based in florida,
You can reach me at shawn@whitefairapps.com, we are ready to help you anytime.

Thanks,
Shawn-

**Comment by dscotese** [comment]
Thanks Shawn and Shepherd.  I believe that you can start with a free mobile-responsive WP theme (like https://wordpress.org/themes/responsive-mobile/) and identify the settings that will make it look like the current site.  I'm still discussing with Steve how best to handle the fact that we will want WP to keep itself updated and don't need to track WP code changes (WP has its own Github project: https://github.com/WordPress/WordPress), but we DO want to track changes to the theme files.

**Comment by dooglio** [comment]
Many popular Wordpress themes are automatically mobile-friendly. For example, check out my site: http://dooglio.wordpress.com
